# Compile Test

name: Compile Test
on:
  pull_request:
    branches:
      - master
      - feature

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17.0.1'
          java-package: jdk
          architecture: x64
      
      - name: Check for compile errors
        run: javac ./src/engine/*.java ./src/entity/*.java ./src/screen/*.java -d ./out
